# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'IDAO' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IDAO
  pod 'Eureka', '~> 5.2'
  pod 'KeychainSwift', '~> 19.0'
end
